Total re-org of logging, and adding the first cut at a config file. NeucaD now requires parameters as well, and can run in the foreground, if desired, for debugging.

diff --git a/neuca-py/debian/neuca-guest-tools.neuca.init b/neuca-py/debian/neuca-guest-tools.neuca.init
--- a/neuca-py/debian/neuca-guest-tools.neuca.init
+++ b/neuca-py/debian/neuca-guest-tools.neuca.init
@@ -18,6 +18,8 @@ PATH=/sbin:/usr/sbin:/bin:/usr/bin
 DESC="NEucaD post-boot configuration daemon"
 NAME=neuca
 NEUCAD=/usr/bin/neucad
+RUNDIR=/var/lib/$NAME
+LOGDIR=/var/log/$NAME
 
 # Read configuration variable file if it is present
 [ -r /etc/default/$NAME ] && . /etc/default/$NAME
@@ -32,27 +34,24 @@ NEUCAD=/usr/bin/neucad
 # Depend on lsb-base (>= 3.0-6) to ensure that this file is present.
 . /lib/lsb/init-functions
 
-#
-# Function that starts the daemon/service
-#
-check_privsep_dir() {
-    # Create the PrivSep empty dir if necessary
-    if [ ! -d /var/run/neuca ]; then
-        mkdir /var/run/neuca
-        mount -t tmpfs -o size=50M,mode=0755,exec tmpfs /var/run/neuca
-        mkdir /var/run/neuca/storage
-    fi
+if [ ! -d "$RUNDIR" ]; then
+    echo "$RUNDIR missing; please check your installation!"
+    exit 1
+fi
 
-    if [ ! -d /var/log/neuca ]; then
-        mkdir /var/log/neuca
-        chmod 0755 /var/log/neuca
-    fi
-}
+if [ ! -d "$LOGDIR" ]; then
+    echo "$LOGDIR missing; please check your installation!"
+    exit 1
+fi
+
+if [ -x "$NEUCAD" ]; then
+    echo "$NEUCAD missing; please check your installation!"
+    exit 1
+fi
+
 
 do_start()
 {
-    check_privsep_dir
-    
     $NEUCAD start
 }
 
diff --git a/neuca-py/redhat/neuca.init b/neuca-py/redhat/neuca.init
--- a/neuca-py/redhat/neuca.init
+++ b/neuca-py/redhat/neuca.init
@@ -39,31 +39,27 @@ PIDFILE=/var/run/$NAME.pid
 SCRIPTNAME=/etc/init.d/$NAME
 NEUCASCRIPT=/etc/neuca/user-script
 NEUCAD=/usr/bin/$prog
+RUNDIR=/var/lib/$NAME
+LOGDIR=/var/log/$NAME
 
-# Exit if the package is not installed
-[ -x "$NEUCAD" ] || exit 0
+if [ ! -d "$RUNDIR" ]; then
+    echo "$RUNDIR missing; please check your installation!"
+    exit 1
+fi
 
-#
-# Function that starts the daemon/service
-#
-check_privsep_dir() {
-    # Create the PrivSep empty dir if necessary
-    if [ ! -d /var/run/neuca ]; then
-        mkdir /var/run/neuca
-        mount -t tmpfs -o size=50M,mode=0755,exec tmpfs /var/run/neuca
-        mkdir /var/run/neuca/storage
-    fi
+if [ ! -d "$LOGDIR" ]; then
+    echo "$LOGDIR missing; please check your installation!"
+    exit 1
+fi
 
-    if [ ! -d /var/log/neuca ]; then
-        mkdir /var/log/neuca
-        chmod 0755 /var/log/neuca
-    fi
-}
+if [ -x "$NEUCAD" ]; then
+    echo "$NEUCAD missing; please check your installation!"
+    exit 1
+fi
+
 
 do_start()
 {
-    check_privsep_dir
-    
     $NEUCAD start
 }
 
